export const productData = [
  {
    id: 1,
    title: "Syltherine",
    sub_title: "Stylish cafe chair",
    price: "2.500.000",
    discount: "3.500.000",
    percentage: "-30%",
    img: "http://localhost:5173/src/assets/images/image.png",
    oImg1: "http://localhost:5173/src/assets/images/Outdoor_sofa_set.png",
    oImg2: "http://localhost:5173/src/assets/images/Outdoor_sofaset.png",
    oImg3: "http://localhost:5173/src/assets/images/Maya_sofa_three_seater.png",
    oImg4: "http://localhost:5173/src/assets/images/Stuart_sofa.png",
    rate: 4,
    review: 5,
    desc: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a 		compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    size: "large",
    sku: "SS001",
    category: "Sofas",
    tags: "Sofa, Chair, Home, Shop",
  },
  {
	id: 2,
    title: "Leviosa",
    sub_title: "Stylish cafe chair",
    price: "2.500.000",
    discount: "",
    percentage: "",
    img: "http://localhost:5173/src/assets/images/image2.png",
    oImg1: "http://localhost:5173/src/assets/images/image.png",
    oImg2: "http://localhost:5173/src/assets/images/image.png",
    oImg3: "http://localhost:5173/src/assets/images/image.png",
    oImg4: "http://localhost:5173/src/assets/images/image.png",
    rate: 4,
    review: 5,
    desc: "Hirem consectetur adipisicing elit. Recusandae debitis voluptate exercitationem accusantium, consectetur libero aspernatur neque fugit quo animi aliquam, temporibus maiores eveniet suscipit ducimus quas ullam, adipisci explicabo.",
    size: "large",
    sku: "SS001",
    category: "Sofas",
    tags: "Sofa, Chair, Home, Shop",
  },
  {
	id: 3,
    title: "Lolito",
    sub_title: "Luxury big sofa",
    price: "7.000.000",
    discount: "3.500.000",
    percentage: "-50%",
    img: "http://localhost:5173/src/assets/images/image3.png",
    oImg1: "http://localhost:5173/src/assets/images/image.png",
    oImg2: "http://localhost:5173/src/assets/images/image.png",
    oImg3: "http://localhost:5173/src/assets/images/image.png",
    oImg4: "http://localhost:5173/src/assets/images/image.png",
    rate: 4,
    review: 5,
    desc: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a 		compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    size: "large",
    sku: "SS001",
    category: "Sofas",
    tags: "Sofa, Chair, Home, Shop",
  },
  {
	id: 4,
    title: "Respira",
    sub_title: "Outdoor bar table and stool",
    price: "500.000",
    discount: "",
    percentage: "New",
    img: "http://localhost:5173/src/assets/images/image4.png",
    oImg1: "http://localhost:5173/src/assets/images/image.png",
    oImg2: "http://localhost:5173/src/assets/images/image.png",
    oImg3: "http://localhost:5173/src/assets/images/image.png",
    oImg4: "http://localhost:5173/src/assets/images/image.png",
    rate: 4,
    review: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae debitis voluptate exercitationem accusantium, consectetur libero aspernatur neque fugit quo animi aliquam, temporibus maiores eveniet suscipit ducimus quas ullam, adipisci explicabo.",
    size: "large",
    sku: "SS001",
    category: "Sofas",
    tags: "Sofa, Chair, Home, Shop",
  },
  {
	id: 5,
    title: "Grifo",
    sub_title: "Night lamp",
    price: "2.500.000",
    discount: "1.500.000",
    percentage: "",
    img: "http://localhost:5173/src/assets/images/image5.png",
	oImg1: "http://localhost:5173/src/assets/images/image.png",
    oImg2: "http://localhost:5173/src/assets/images/image.png",
    oImg3: "http://localhost:5173/src/assets/images/image.png",
    oImg4: "http://localhost:5173/src/assets/images/image.png",
    rate: 4,
    review: 5,
    desc: "Adipisicing elit. Recusandae debitis voluptate exercitationem accusantium, consectetur libero aspernatur neque fugit quo animi aliquam, temporibus maiores eveniet suscipit ducimus quas ullam, adipisci explicabo.",
    size: "large",
    sku: "SS001",
    category: "Sofas",
    tags: "Sofa, Chair, Home, Shop",
  },
  {
	id: 6,
    title: "Muggo",
    sub_title: "Small mug",
    price: "1.50.000",
    discount: "3.500.000",
    percentage: "New",
    img: "http://localhost:5173/src/assets/images/image6.png",
	oImg1: "http://localhost:5173/src/assets/images/image.png",
    oImg2: "http://localhost:5173/src/assets/images/image.png",
    oImg3: "http://localhost:5173/src/assets/images/image.png",
    oImg4: "http://localhost:5173/src/assets/images/image.png",
    rate: 4,
    review: 5,
    desc: "consectetur adipisicing elit. Recusandae debitis voluptate exercitationem accusantium, consectetur libero aspernatur neque fugit quo animi aliquam, temporibus maiores eveniet suscipit ducimus quas ullam, adipisci explicabo.",
    size: "large",
    sku: "SS001",
    category: "Sofas",
    tags: "Sofa, Chair, Home, Shop",
  },
  {
	id: 7,
    title: "Pingky",
    sub_title: "Cute bed set",
    price: "7.000.000",
    discount: "3.500.000",
    percentage: "-50%",
    img: "http://localhost:5173/src/assets/images/image7.png",
  },
  {
	id: 8,
    title: "Potty",
    sub_title: "Minimalist flower pot",
    price: "500.000",
    discount: "3.500.000",
    percentage: "New",
    img: "http://localhost:5173/src/assets/images/image8.png",
  },
];
